#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\BplanController::index

article_add:
  path: /add
  controller: App\Controller\BplanController::add

article_show:
  path: /show/{id}
  controller: App\Controller\BplanController::show

article_edit:
  path: /edit/{id}
  controller: App\Controller\BplanController::edit
  requirements:
    id: '\d+'

article_remove:
  path: /remove/{id}
  controller: App\Controller\BplanController::remove
  requirements:
    id: '\d+'


admin:
  path: /admin
  controller: App\Controller\BplanController::admin